version: '3.3'

services:
  web:
    build: .
#    command: daphne MyFruitShop.asgi:application
    command:  uvicorn MyFruitShop.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - static_volume:/usr/src/MyFruitShop/static
      - media_volume:/usr/src/MyFruitShop/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=danil
      - POSTGRES_PASSWORD=danil
      - POSTGRES_DB=fruit_shop
  redis:
    image: redis:alpine
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/MyFruitShop/static
      - media_volume:/usr/src/MyFruitShop/media
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: