version: '3.3'

services:
  web:
    build: .
    command:  uvicorn MyFruitShop.asgi:application --host 0.0.0.0 --port 8000 --workers 1
    volumes:
      - static_volume:/usr/src/MyFruitShop/static
      - media_volume:/usr/src/MyFruitShop/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/MyFruitShop/static
      - media_volume:/usr/src/MyFruitShop/media
    ports:
      - "1337:80"
    depends_on:
      - web
  redis:
    image: redis:alpine
volumes:
  postgres_data:
  static_volume:
  media_volume: