version: '3.3'

services:
  web:
    build :
      context: .
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 MyFruitShop.asgi:application
    volumes:
      - static_volume:/home/MyFruitShop/web/static
      - media_volume:/home/MyFruitShop/web/media
    expose:
      - 8000
    depends_on:
      - db
      - daphne

    env_file:
      - ./.env.prod
  daphne:
    build:
      context: ./
    image: daphne:test
    ports:
      - "8080:8080"
      - "8000:8000"
    container_name: daphne_server
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/MyFruitShop/web/static
      - media_volume:/home/MyFruitShop/web/media
    ports:
      - "1337:80"
    depends_on:
      - web
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    restart: always
  celery:
    restart: always
    build:
      context: .
    command: celery -A MyFruitShop worker -Q trading_queue,celery -l  info --concurrency=1
    volumes:
      - .:/home/MyFruitShop/web/
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A MyFruitShop beat
    env_file:
      - ./.env.prod
    depends_on:
      - celery
volumes:
  cache:
  postgres_data:
  static_volume:
  media_volume:
