# Generated by Django 4.2.6 on 2023-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_message_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
