# Generated by Django 4.2.6 on 2023-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_rename_balance_fruitstorage_amount_fruitstorage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationjournal',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=10, null=True),
        ),
    ]
