# Generated by Django 4.2.6 on 2023-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_fruitstorage_price_alter_operationjournal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationjournal',
            name='name',
        ),
        migrations.AddField(
            model_name='operationjournal',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationjournal',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationjournal',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10, null=True),
        ),
    ]
