# Generated by Django 4.2.6 on 2023-10-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_operationjournal_name_operationjournal_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationjournal',
            options={'ordering': ['timestamp']},
        ),
    ]
