# Generated by Django 4.2.6 on 2023-11-02 17:04

import admin_panel.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_operationjournal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=admin_panel.utilities.get_timestamp_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'declaration',
            },
        ),
        migrations.AlterModelOptions(
            name='fruitstorage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='operationjournal',
            options={'ordering': ['-timestamp']},
        ),
    ]
