# Generated by Django 4.2.6 on 2023-11-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_declaration_alter_fruitstorage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
