# Generated by Django 4.2.6 on 2023-11-04 17:59

import admin_panel.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_delete_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='declaration',
            name='file',
            field=models.FileField(upload_to=admin_panel.utilities.get_timestamp_path, verbose_name=''),
        ),
    ]
